name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    strategy:
      fail-fast: false
      matrix:
        name:
          - stable
          - beta
          - Windows
          - MacOS

        include:
          - name: beta
            toolchain: beta
          - name: Windows
            os: windows-latest
          - name: MacOS
            os: macos-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        run: |
          rustup install --profile minimal ${{ matrix.toolchain || 'stable' }}
          rustup override set ${{ matrix.toolchain || 'stable' }}
      - name: Add problem matchers
        shell: bash
        run: echo "::add-matcher::.github/matchers/rust.json"

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
